### ISSUE TITLE
Add sort filter in the website

### ISSUE THREAD

**Issue by spyrou008** [macmillen/gfn-epic#1]
Great work, 
I can see the website offers by default the game list sorted by "release" the date/week when the game was free on EGS. 
It would be great to be able to sort by any column , 
especially : Date (default) , or Game Title , or the Game rating 
ascending or descending
with or without the GFN filter ON/OFF. 
Cheers

**Comment by macmillen** [comment]
I added a sort by rating switch but I don't think that sort by game title is really useful right now so in order to keep it simple I leave it for now

**Comment by spyrou008** [comment]
Thank you for your efforts and this new update. 
FYI: sorting by game title may sound optional to you. but if it was asked , it's because there is a need behind. 
Now I understand that you want to keep the website as clean as possible . This is really great philosophy. (KISS principle) 
I just wish that the Export into CSV or Excel-like format will be available in a future release , so that I can sort by game title (offline), and also by Epic Game ID (or GFN Game ID). so that I can manage the games I own and their details.
