### ISSUE TITLE
Game Link on the GFN icon

### ISSUE THREAD

**Issue by spyrou008** [macmillen/gfn-epic#2]
Great work , 
Could you add an hyperlink on the GFN icon for games which are available in GFN ?
( I am asking as you may already have the GFN game id whilst collecting info )
Eg: for Warpips
https://play.geforcenow.com/games?game-id=371d48dd-9f24-4b91-9caa-b9e8e3380c3c

Cheers

**Comment by macmillen** [comment]
done with the latest released :)
