### ISSUE TITLE
Ability to extract the data

### ISSUE THREAD

**Issue by spyrou008** [macmillen/gfn-epic#3]
Great work, 
Would you consider creating a CSV extract, please ?
i.e.: an export into a text file , with details that are coma separated.

eg:
EGS App name , Game , Release start date , Release end date , Is Game GFN supported , GFN game-id , Genre 1 , Genre 2 , Metacritic rating , EGS link , GFN link , Other details from EGS if possible (like : Release Date ( 04/21/22 ) / Features / Controller Support / Single Player ) , Other details from GFN if possible (like : Release Date ( 04/21/22 ) / PEGI rating (16) / Inputs / Nb of players / Genres )
1f695dfd76d8438d8dd4046fe75daab0 , Warpips , 44973 , 44980 , 1 , 371d48dd-9f24-4b91-9caa-b9e8e3380c3c , Real Time Strategy (RTS) , Strategy , NA , https://store.epicgames.com/en-US/p/warpips-57e2c4 , https://play.geforcenow.com/games?game-id=371d48dd-9f24-4b91-9caa-b9e8e3380c3c ,  ,
fc0b13b7b17b4a46933756fb2786cdc4 , Chess Ultra , 45008 , 45015 , 0 ,  , Puzzle , Simulator , 72 , https://store.epicgames.com/en-US/p/chess-ultra-91bba3 ,  ,  ,

Note: in the example above , I added spaces to ease the reading for a human. these spaces will need to be removed. 

Cheers

**Comment by macmillen** [comment]
Hey, I guess a json should also be serving this purpose.

https://github.com/macmillen/gfn-epic/blob/master/src/data/generated/4-final-data.json

**Comment by spyrou008** [comment]
I guess it could work , thanks for that. 

Can I ask where do you get the game id ? 
eg: Warpips id: 146438
```
    "title": "Warpips",
    "gfnUrl": "https://play.geforcenow.com/games?game-id=371d48dd-9f24-4b91-9caa-b9e8e3380c3c",
    "id": 146438,
    "data": {
      "id": 146438,
```

and : do you have access to the Epic Game `App Name` ?
I use the `legendary` tool, which gives me: 
Warpips App name: 1f695dfd76d8438d8dd4046fe75daab0
I guess this is given by the EGS API that `legendary` uses. 

at some point , I would like to reconcile both lists, with a unique ID.

**Comment by macmillen** [comment]
The id comes from the [igdb database](https://api-docs.igdb.com/).

I don't have access to the Epic Game App Name though.
