### ISSUE TITLE
Ability to get details in the JSON file: the PEGI rating

### ISSUE THREAD

**Issue by spyrou008** [macmillen/gfn-epic#4]
Hi, 
In your JSON file, you have plenty of great details. `genres` is one of them. 

I would like to know if it is possible to get the PEGI rating too ?
This could also be used later, if you want to add a little icon, next to the game title. 

FYI I got these PEGI ratings from the GFN website : 
- Absolute Drift: Zen Edition -> PEGI 3
- Alan Wake's American Nightmare -> PEGI 18

Thank you in advance

**Comment by macmillen** [comment]
I added the age ratings to the json. You can find the corresponding enum values here:
https://api-docs.igdb.com/#age-rating
